---
title: "*Ghost in the Shell*, Cities and Modernity in Japan"
author:   
  - name: Lexun Yu
date: "October 1, 2023"
bibliography: references.bib
---

*Ghost in the Shell* is a Japanese science fiction movie directed by @oshiiKokakuKidotai1996 in 1995. It tells a story about a policewomen called Major Motoko Kusanagi investigating a multinational hacking on cyborgs. Major Kusanagi is a cyborg, she has a human brain but an artificial body. The story takes place in a city called New Port city. Major Kusanagi, Batou and the Section 9 team found a hacker called Puppet Master. Puppet Master can hack into people’s brain and manipulate their thoughts. Upon the investigation, Major Motoko realized that the Puppet Master is an Artificial Intelligence created by Section 6 with a code name 2501 which is a project aim to create a new form of artificial life. The hacking event is also related to a series of mysterious murders involving powerful government officials. During Major Motoko’s conversation with Puppet Master, she discovers Puppet master’s true desires. Puppet Master wants to merge with human consciousness and have a true self. Meanwhile, Major Kusanagi was also questioning her humanity. At the end of the movie, when Section 6 hunts down Puppet Master and Kusanagi, they merge their consciousnesses and turn into an AI with consciousness. In the movie, there is a strong connection between the film’s space and geography, and the urban life is a mixture of tradition and modernity. The movie raises the problem in identity of Japanese cities and individuals in cities. The movie is targeted to the masses in Japan which is deeply influenced by modernity. 

In the book chapter L.A. Noir, @hausladenNoir2005 analyze the relationship between the characters and plots of film noir and Los Angeles as a city. The same film space connection can be found in the Ghost in the Shell. According to Manny Farber, The three types of film space are “(1) the field of the screen, (2) the psychological space of the actor, and (3) the area of experience and geography that the film covers (Hausladen & Starrs, 2005, p. 43).” Hausladen and Starrs argued that environmental determinism has a profound effect on the medium of movie. There is a strong connection between the city that serves as the setting for the story and the psychological space of the characters. The characters in the movies are shaped by the environment they live in. For instance, “dingy alleys and awful days and wicked dialogue and disconsolate weather all presumably added up to damp, if not dyspeptic, souls, [@hausladenNoir2005 p. 47]” according to Hausladen and Starrs. This effect of environmental determinism can also be found in *Ghost in the Shell*. 

The film's Hong Kong-like urban environment influences the characters in the movie. The story of *Ghost in the Shell* happens in the cyberpunk future. But this futuristic city isn't exactly glamorous. People are transformed into partial machines to different extents. At the beginning of the movie, Kusanagi wakes up from a neat room and carries out her mission with high-tech equipment such as optical camouflage. For the average citizens, their bodies have undergone fewer modifications. Government workers are also better equipped and have a better living environment. Average people live in dirty and dim alleys, the buildings in these areas are very old and the roads are badly damaged [@oshiiKokakuKidotai1996]. 

However, these people of different incomes and social classes live in the same city and are oblivious to each other. This depiction of the environment defines all characters’ psychological space. The city in this movie shares numerous similarities to Hong Kong, as many of the signs in the show have traditional Chinese characters on them. @yuenEdgeSpacesBlade2000 analyzed the close relation between social space and identity in Hong Kong in the article *On the Edge of Spaces*. The Times Square is the busiest district in Hong Kong. It is a blend of old and new architecture. New commercialized buildings are built in neighborhoods of old buildings inhabited by people with low incomes. There are a lot of empty shots in the movie of the crumbling landscapes of the city, new billboards and stores are opening between these old buildings, which matches Yuen’s description of Hong Kong. The effect of this landscape is a harmonious environment for people of different income and races to live in. This postmodern environment is a very different one from the one depicted in American film noir. According to Yuen, “More than Disneyland, … this absolute accessibility to the fairyland of diversity and display accounts for its success. [@yuenEdgeSpacesBlade2000, p. 6]” This is the opposite of the deliberate urban landscape in the United States, where separate people from each other. Like the city, people are changed to cyborgs, modified by new technologies, and human body parts co-exist with machines.

This mixture of old and new buildings in the city and of people and machines in the city represents the attitude of Japanese people towards modernization after war. Modernity in Japan is a contentious issue that has been discussed for many years. It centers on the issue of how Japan should accept modernization and adapt to it, particularly considering the country's quick transformation during the Meiji Restoration and later decades. Modernist such as Otsuka Hisao encouraged Japanese people to embrace civilization and enlightenment [@koschmannDebateSubjectivityPostwar1981, p. 625]. 

Among them were also those who championed traditional Japanese culture, such as @yanagitaLegendsTono2008. Yanagita wrote *Legend of Tono* in 1910, chronicled the legend of a Japanese village called Tono, and Yanagita also pointed out in Preface that Japanese people should find their identity in the Japanese countryside, where traditions exists [@yanagitaLegendsTono2008, p. 7]. About 40 years before the release of Ghost in the Shell, the destruction of Tokyo by a monster [@hondaGojira1954] in Godzilla reflects Japan's fear of modernization and the United States [@noriegaGodzillaJapaneseNightmare1987, p. 61].

*Ghost in the Shell* demonstrates an alternative way of being for modernization and tradition. As mentioned in the previous paragraph, The new building is built on top of the old one, where traditional human body parts and machines exist in the same body at the same time. This movie uncovered Japan’s new relationship with modernity. Japan has incorporated modernity and grafted it atop already-existing traditions. Modernity's glamour has entered popular culture in cities, while tradition remains in the shadows. A wide array of signs and cluttered spaces exists everywhere, the sounds of cars, crowds and markets in the city force their way into the ears of every urban resident. In the movie, the inhabitants of the city are completely unresponsive to the sight of a landscape heavily impacted by modernity and a Kusanagi that has been nearly completely transformed by machines. As Yuen mentioned, “the artificial has replaced the natural, humans are like animals in the past, deprived of the characteristics of being human as a whole … their feelings are henceforth numbed [@yuenEdgeSpacesBlade2000, p. 14].” Both the city and citizens are used to this intrusion of modernity. Therefore, at this time, the Japanese in the city did not have a complete acceptance or a complete rejection of modernity. Modernity was integrated into the city, among the Japanese, creating a kind of numbness. Japan’s national identity has become part of modernity, “like one of the silky threads of the spider web [@yuenEdgeSpacesBlade2000, p. 14].” 

The intended audiences of *Ghost in the Shell* should be Japanese people in the cities. As mentioned in the previous paragraphs, The overexposed modernity creates a sense of numbness for those living in the city. In one of the movie's scenes, As Kusanagi makes her way through the city, she sees a person in a window that looks just like herself. Later, Kusanagi and Batou exchange words on a boat outside of town. Kusanagi begins to question who she is herself. She was questioning what a person is consciousness and identity is. Kusanagi's struggles with the mechanical and human aspects of her body are simultaneously Japanese struggles with their own identity. After experiencing war, atomic war, occupation by the US and “overcoming modernity”, Japan as a nation has incorporated modernity into itself. The examination of the city through the lens of Kusanagi in the movie provides a new perspective for Japanese people. makes Japanese people re-examine Japan's identity from a third person’s perspective.

In conclusion, Japan's urban environment combines traditional and modern aspects. The issue of identity is examined in relation to Japanese cities and the inhabitants of them. The Japanese populace, which is strongly influenced by modernity, makes up its main audience.